class GL;
GLenum
GLenum
GLenum
GLdouble
GLenum

GLenum
GLfloat
GLenum

GLenum
GLint
GLenum

GLenum
GLshort
GLenum

GLenum
GLdouble
GLdouble
GLenum

GLenum
GLfloat
GLfloat
GLenum

GLenum
GLint
GLint
GLenum

GLenum
GLshort
GLshort
GLenum

GLenum
GLdouble
GLdouble
GLdouble
GLenum

GLenum
GLfloat
GLfloat
GLfloat
GLenum

GLenum
GLint
GLint
GLint
GLenum

GLenum
GLshort
GLshort
GLshort
GLenum

GLenum
GLdouble
GLdouble
GLdouble
GLdouble
GLenum

GLenum
GLfloat
GLfloat
GLfloat
GLfloat
GLenum

GLenum
GLint
GLint
GLint
GLint
GLenum

GLenum
GLshort
GLshort
GLshort
GLshort
GLenum





GLclampf
GLboolean
GLenum
GLenum
GLint
GLenum
GLsizei
GLsizei
GLsizei
GLint
GLsizei

GLenum
GLint
GLenum
GLsizei
GLsizei
GLint
GLsizei

GLenum
GLint
GLenum
GLsizei
GLint
GLsizei

GLenum
GLint
GLint
GLint
GLint
GLsizei
GLsizei
GLsizei
GLenum
GLsizei

GLenum
GLint
GLint
GLint
GLsizei
GLsizei
GLenum
GLsizei

GLenum
GLint
GLint
GLsizei
GLenum
GLsizei

GLenum
GLint
GLvoid
GLint

GLint

GLint

GLint

GLint

GLint

GLint

GLint

GLint
GLenum
GLsizei

GLint
GLdouble
GLdouble

GLfloat
GLfloat

GLint
GLint

GLshort
GLshort

GLdouble
GLdouble
GLdouble

GLfloat
GLfloat
GLfloat

GLint
GLint
GLint

GLshort
GLshort
GLshort

GLsizei
GLuint
GLsizei

GLuint
GLenum
GLuint
GLenum
GLenum
GLenum
GLint
GLuint
GLenum
GLint
GLuint
GLenum
GLuint
GLenum
GLfloat
GLenum

GLenum
GLuint
GLsizei

GLsizei
GLuint
GLuint
GLenum
GLuint
GLdouble
GLdouble
GLdouble
GLdouble
GLenum
GLuint

GLenum
GLuint
GLfloat
GLfloat
GLfloat
GLfloat
GLenum
GLuint

GLenum
GLuint
GLdouble
GLdouble
GLdouble
GLdouble
GLenum
GLuint

GLenum
GLuint
GLfloat
GLfloat
GLfloat
GLfloat
GLenum
GLuint

GLenum
GLuint
GLdouble
GLenum
GLuint
GLfloat
GLenum
GLuint
GLsizei

GLenum
GLuint
GLsizei

GLenum
GLuint
GLdouble
GLenum
GLuint
GLfloat
GLenum
GLenum
GLsizei

GLenum
GLenum
GLvoid
GLenum
GLenum
GLint
GLuint
GLdouble
GLuint

GLuint
GLfloat
GLuint

GLuint
GLshort
GLuint

GLuint
GLdouble
GLdouble
GLuint

GLuint
GLfloat
GLfloat
GLuint

GLuint
GLshort
GLshort
GLuint

GLuint
GLdouble
GLdouble
GLdouble
GLuint

GLuint
GLfloat
GLfloat
GLfloat
GLuint

GLuint
GLshort
GLshort
GLshort
GLuint

GLuint

GLuint

GLuint

GLuint
GLubyte
GLubyte
GLubyte
GLubyte
GLuint

GLuint

GLuint

GLuint

GLuint
GLdouble
GLdouble
GLdouble
GLdouble
GLuint

GLuint
GLfloat
GLfloat
GLfloat
GLfloat
GLuint

GLuint

GLuint
GLshort
GLshort
GLshort
GLshort
GLuint

GLuint

GLuint

GLuint

GLuint
GLint
GLenum
GLboolean
GLsizei

GLuint
GLuint
GLuint
GLenum
GLvoid
GLuint
GLenum
GLdouble
GLuint
GLenum
GLfloat
GLuint
GLenum
GLint
GLhandleARB
GLenum
GLhandleARB
GLhandleARB
GLenum
GLhandleARB
GLsizei


GLhandleARB
void
GLhandleARB
GLhandleARB
GLhandleARB
GLhandleARB
GLhandleARB
GLint
GLfloat
GLint
GLfloat
GLfloat
GLint
GLfloat
GLfloat
GLfloat
GLint
GLfloat
GLfloat
GLfloat
GLfloat
GLint
GLint
GLint
GLint
GLint
GLint
GLint
GLint
GLint
GLint
GLint
GLint
GLint
GLint
GLint
GLsizei

GLint
GLsizei

GLint
GLsizei

GLint
GLsizei

GLint
GLsizei

GLint
GLsizei

GLint
GLsizei

GLint
GLsizei

GLint
GLsizei
GLboolean

GLint
GLsizei
GLboolean

GLint
GLsizei
GLboolean

GLhandleARB
GLenum
GLfloat
GLhandleARB
GLenum
GLint
GLhandleARB
GLsizei
GLsizei
GLcharARB
GLhandleARB
GLsizei
GLsizei
GLhandleARB
GLhandleARB

GLhandleARB
GLuint
GLsizei
GLsizei
GLint
GLenum
GLcharARB
GLhandleARB
GLint
GLfloat
GLhandleARB
GLint
GLint
GLhandleARB
GLsizei
GLsizei
GLcharARB
GLhandleARB
GLuint

GLhandleARB
GLuint
GLsizei
GLsizei
GLint
GLenum
GLcharARB
GLhandleARB

GLenum
GLuint
GLsizei

GLsizei
GLuint
GLuint
GLenum
GLsizeiptrARB

GLenum
GLenum
GLintptrARB
GLsizeiptrARB

GLenum
GLintptrARB
GLsizeiptrARB
GLvoid
GLenum
GLenum
GLenum
GLenum
GLenum
GLint
GLenum
GLenum
GLvoid
GLsizei

GLclampf
GLclampf
GLclampf
GLclampf
GLenum
GLenum
GLenum
GLsizei
GLenum
GLenum

GLenum
GLsizei
GLsizei
GLenum
GLenum

GLenum
GLenum
GLenum
GLvoid
GLenum
GLenum
GLint
GLenum
GLenum
GLfloat
GLint
GLsizei
void
GLenum
GLuint
GLuint
GLsizei
GLenum

GLbyte
GLbyte
GLbyte

GLdouble
GLdouble
GLdouble

GLfloat
GLfloat
GLfloat

GLint
GLint
GLint

GLshort
GLshort
GLshort

GLubyte
GLubyte
GLubyte

GLuint
GLuint
GLuint

GLushort
GLushort
GLushort

GLint
GLenum
GLsizei

GLenum


GLsizei
GLenum

GLenum

GLsizei
GLfloat

GLdouble

GLenum
GLsizei

GLenum
GLenum
GLenum
GLenum
GLenum
GLclampd
GLclampd
GLenum
GLenum
GLuint
GLenum
GLuint
GLsizei

GLsizei
GLuint
GLenum
GLenum
GLsizei
GLsizei
GLenum
GLenum
GLint
GLuint
GLenum
GLuint
GLsizei

GLsizei
GLuint
GLenum
GLenum
GLenum
GLenum
GLuint
GLint
GLenum
GLenum
GLenum
GLuint
GLint
GLenum
GLenum
GLenum
GLuint
GLint
GLint
GLenum
GLenum
GLenum
GLuint
GLenum
GLenum
GLenum
GLint
GLenum
GLint
GLint
GLint
GLint
GLint
GLint
GLint
GLint
GLbitfield
GLenum
GLenum
GLsizei
GLenum
GLsizei
GLsizei
GLuint
GLenum
GLint
GLenum
GLenum
GLuint
GLint
GLenum
GLenum
GLuint
GLint
GLint
GLenum
GLenum
GLuint
GLint
GLenum
GLenum
GLuint
GLuint
GLintptr
GLsizeiptr
GLenum
GLuint
GLuint
GLintptr
GLenum
GLuint
GLuint
GLenum
void
GLuint
GLsizei

GLenum
GLuint
GLuint
GLsizei
GLsizei
GLsizei
GLenum
GLchar
GLenum
GLuint
GLint
GLenum
GLuint
GLboolean
GLuint
GLint
GLuint
GLuint
GLint
GLuint
GLint
GLint
GLint
GLint
GLint
GLuint
GLuint
GLuint
GLuint
GLenum
GLenum
GLint
GLenum
GLenum
GLuint
GLenum
GLenum
GLint
GLenum
GLenum
GLuint
GLuint
GLint
GLuint
GLint
GLint
GLuint
GLint
GLint
GLint
GLuint
GLint
GLint
GLint
GLint
GLuint
GLuint
GLuint
GLuint
GLuint
GLuint
GLuint
GLuint
GLuint
GLuint
GLuint
GLuint
GLuint
GLuint
GLuint

GLuint

GLuint

GLuint

GLuint

GLuint

GLuint

GLuint

GLuint

GLuint

GLuint

GLuint

GLuint
GLint
GLenum
GLsizei

GLuint
GLenum
GLint
GLuint
GLenum
GLuint
GLint
GLuint
GLint
GLuint
GLuint
GLint
GLuint
GLuint
GLuint
GLint
GLuint
GLuint
GLuint
GLuint
GLint
GLsizei

GLint
GLsizei

GLint
GLsizei

GLint
GLsizei

GLuint
GLint
GLuint
GLuint
GLuint

GLuint

GLenum
GLsizei

GLenum
GLenum
GLvoid
GLsizei

GLsizei

GLenum
GLint
GLuint
GLsizei

GLsizei
GLuint
GLuint
GLsizei
GLuint
GLsizei

GLuint
GLuint
GLuint
GLuint
GLenum
GLuint
GLenum
GLuint
GLenum

GLenum
GLint
GLsizei
GLenum
GLuint
GLuint
GLint
GLsizei
GLenum


GLsizei
GLenum
GLuint
GLuint


GLsizei
void
void
void
GLuint
GLenum
GLuint
GLenum
GLuint
GLenum
GLuint
GLuint
GLdouble
GLdouble
GLint
GLint

GLuint
GLuint
GLfloat
GLfloat
GLint
GLint

GLuint
GLuint
GLdouble
GLdouble
GLint
GLint
GLdouble
GLdouble
GLint
GLint

GLuint
GLuint
GLfloat
GLfloat
GLint
GLint
GLfloat
GLfloat
GLint
GLint

GLenum
GLenum
GLint
GLenum
GLintptr
GLsizeiptr
GLenum
GLuint
GLenum
GLenum
GLuint
GLenum
GLenum
GLuint
GLenum
GLint*
GLenum
GLint
GLenum
GLfloat
GLenum
GLenum
GLenum
GLenum
GLenum
GLenum
GLenum
GLenum
GLint
GLuint
GLenum
GLint
GLenum
GLfloat
GLenum

GLenum
GLfloat
GLenum

GLenum
GLint
GLenum
GLenum
GLenum
GLenum
GLenum
GLenum
GLenum
GLenum
GLenum
GLenum
GLenum
GLenum
GLenum
GLboolean
GLboolean
GLboolean
GLenum
GLenum
GLenum
GLenum
GLenum
GLenum
GLenum
GLenum
GLfloat
GLenum
GLenum
GLenum
GLenum
GLint
GLenum
GLenum
GLenum
GLfloat
GLenum
GLenum
GLenum
GLint
GLenum
GLenum
GLfloat
GLenum
GLenum
GLint
GLenum
GLenum

GLenum
GLenum
GLfloat
GLenum
GLint
GLenum

GLenum
GLfloat
GLenum
GLclampf
GLsizei

GLboolean
GLint
GLenum
GLenum
GLuint
GLsizei
GLsizei
GLfloat
GLfloat
GLfloat
GLfloat

GLclampf
GLclampf
GLclampf
GLclampf
GLenum
GLenum
GLenum
GLenum
GLenum
GLuint
GLsizei
GLenum

GLbitfield
GLfloat
GLfloat
GLfloat
GLfloat
GLclampf
GLclampf
GLclampf
GLclampf
GLclampd
GLfloat
GLint
GLenum

GLbyte
GLbyte
GLbyte

GLdouble
GLdouble
GLdouble

GLfloat
GLfloat
GLfloat

GLint
GLint
GLint

GLshort
GLshort
GLshort

GLubyte
GLubyte
GLubyte

GLuint
GLuint
GLuint

GLushort
GLushort
GLushort

GLbyte
GLbyte
GLbyte
GLbyte

GLdouble
GLdouble
GLdouble
GLdouble

GLfloat
GLfloat
GLfloat
GLfloat

GLint
GLint
GLint
GLint

GLshort
GLshort
GLshort
GLshort

GLubyte
GLubyte
GLubyte
GLubyte

GLuint
GLuint
GLuint
GLuint

GLushort
GLushort
GLushort
GLushort

GLboolean
GLboolean
GLboolean
GLboolean
GLenum
GLenum
GLint
GLenum
GLsizei

GLenum
GLsizei
GLsizei
GLenum
GLenum

GLenum
GLenum
GLsizei
GLenum
GLenum

GLenum
GLenum

GLenum
GLenum

GLenum
GLenum
GLsizei
GLenum
GLenum

GLenum
GLenum
GLsizei
GLsizei
GLenum
GLenum

GLenum
GLenum
GLfloat
GLenum
GLenum

GLenum
GLenum
GLint
GLenum
GLenum

GLenum
GLsizei
GLint
GLint
GLsizei
GLenum
GLenum
GLint
GLint
GLsizei
GLenum
GLenum
GLint
GLint
GLsizei
GLenum
GLenum
GLint
GLint
GLsizei
GLsizei
GLint
GLint
GLsizei
GLsizei
GLenum
GLenum
GLint
GLenum
GLint
GLint
GLsizei
GLint
GLenum
GLint
GLenum
GLint
GLint
GLsizei
GLsizei
GLint
GLenum
GLint
GLint
GLint
GLint
GLsizei
GLenum
GLint
GLint
GLint
GLint
GLint
GLsizei
GLsizei
GLenum
GLint
GLint
GLint
GLint
GLint
GLint
GLsizei
GLsizei
GLenum
GLuint
GLsizei
GLsizei

GLenum
GLboolean
GLclampd
GLclampd
GLenum
GLenum
GLenum
GLint
GLsizei
GLenum
GLenum
GLsizei
GLenum

GLsizei
GLsizei
GLenum
GLenum

GLenum
GLuint
GLuint
GLsizei
GLenum

GLboolean
GLsizei


GLenum
GLenum
void
void
GLdouble

GLfloat

GLdouble
GLdouble

GLfloat
GLfloat

GLenum
GLint
GLint
GLenum
GLint
GLint
GLint
GLint
GLint
GLint
GLint
GLsizei
GLenum
GLfloat
void
void
GLenum
GLfloat
GLenum

GLenum
GLint
GLenum

GLenum
GLdouble
GLdouble
GLdouble
GLdouble
GLdouble
GLdouble
GLsizei
GLsizei
GLuint
GLenum
GLboolean
GLenum
GLdouble
GLenum
GLenum
GLenum
GLvoid
GLenum
GLenum
GLfloat
GLenum
GLenum
GLint
GLenum
GLenum
GLenum
GLvoid
GLenum
GLenum
GLfloat
GLenum
GLenum
GLint
GLenum
GLdouble
void
GLenum
GLfloat
GLenum
GLboolean
GLenum
GLenum
GLvoid
GLenum
GLenum
GLfloat
GLenum
GLenum
GLint
GLenum
GLint
GLenum
GLenum
GLfloat
GLenum
GLenum
GLint
GLenum
GLenum
GLdouble
GLenum
GLenum
GLfloat
GLenum
GLenum
GLint
GLenum
GLenum
GLfloat
GLenum
GLenum
GLint
GLenum
GLboolean
GLenum
GLenum
GLvoid
GLenum
GLenum
GLfloat
GLenum
GLenum
GLint
GLenum
GLfloat
GLenum
GLuint
GLenum
GLushort
GLenum
GLvoid*
GLubyte
GLenum
GLenum
GLenum
GLvoid
GLvoid
GLvoid
GLenum
GLenum
GLfloat
GLenum
GLenum
GLint
GLenum
GLenum
GLdouble
GLenum
GLenum
GLfloat
GLenum
GLenum
GLint
GLenum
GLint
GLenum
GLenum
GLvoid
GLenum
GLint
GLenum
GLfloat
GLenum
GLint
GLenum
GLint
GLenum
GLenum
GLfloat
GLenum
GLenum
GLint
GLenum
GLenum
GLenum
GLsizei
GLenum
GLboolean
GLuint
GLenum
GLsizei

GLdouble

GLfloat

GLint

GLshort

GLubyte

void
GLenum
GLsizei

GLenum
GLuint
GLuint
GLenum
GLfloat
GLenum

GLenum
GLint
GLenum

GLenum
GLenum
GLfloat
GLenum
GLenum

GLenum
GLenum
GLint
GLenum
GLenum

GLint
GLushort
GLfloat
GLuint
void


GLuint
GLenum
GLenum
GLdouble
GLdouble
GLint
GLint

GLenum
GLfloat
GLfloat
GLint
GLint

GLenum
GLdouble
GLdouble
GLint
GLint
GLdouble
GLdouble
GLint
GLint

GLenum
GLfloat
GLfloat
GLint
GLint
GLfloat
GLfloat
GLint
GLint

GLint
GLdouble
GLdouble
GLint
GLfloat
GLfloat
GLint
GLdouble
GLdouble
GLint
GLdouble
GLdouble
GLint
GLfloat
GLfloat
GLint
GLfloat
GLfloat
GLenum
GLenum
GLfloat
GLenum
GLenum

GLenum
GLenum
GLint
GLenum
GLenum

GLenum
GLenum
GLenum
GLboolean


GLuint
GLenum
GLbyte
GLbyte
GLbyte

GLdouble
GLdouble
GLdouble

GLfloat
GLfloat
GLfloat

GLint
GLint
GLint

GLshort
GLshort
GLshort

GLenum
GLsizei

GLdouble
GLdouble
GLdouble
GLdouble
GLdouble
GLdouble
GLfloat
GLenum
GLint

GLenum
GLint

GLenum
GLint

GLenum
GLfloat
GLenum
GLint
GLenum
GLfloat
GLenum
GLint
GLfloat
GLfloat
GLfloat
GLenum
GLenum
GLfloat
GLfloat

void
void
void
void
GLsizei


GLbitfield
GLbitfield
void
GLuint
GLdouble
GLdouble

GLfloat
GLfloat

GLint
GLint

GLshort
GLshort

GLdouble
GLdouble
GLdouble

GLfloat
GLfloat
GLfloat

GLint
GLint
GLint

GLshort
GLshort
GLshort

GLdouble
GLdouble
GLdouble
GLdouble

GLfloat
GLfloat
GLfloat
GLfloat

GLint
GLint
GLint
GLint

GLshort
GLshort
GLshort
GLshort

GLenum
GLint
GLint
GLsizei
GLsizei
GLenum
GLenum
GLvoid
GLdouble
GLdouble
GLdouble
GLdouble


GLfloat
GLfloat
GLfloat
GLfloat


GLint
GLint
GLint
GLint


GLshort
GLshort
GLshort
GLshort


GLenum
GLenum
GLenum
GLdouble
GLdouble
GLdouble
GLdouble
GLfloat
GLfloat
GLfloat
GLfloat
GLdouble
GLdouble
GLdouble
GLfloat
GLfloat
GLfloat
GLint
GLint
GLsizei
GLsizei
GLsizei
GLuint
GLenum
GLenum
GLsizei
GLsizei
GLenum
GLenum


GLenum
GLenum
GLint
GLuint
GLuint
GLenum
GLenum
GLenum
GLdouble

GLfloat

GLint

GLshort

GLdouble
GLdouble

GLfloat
GLfloat

GLint
GLint

GLshort
GLshort

GLdouble
GLdouble
GLdouble

GLfloat
GLfloat
GLfloat

GLint
GLint
GLint

GLshort
GLshort
GLshort

GLdouble
GLdouble
GLdouble
GLdouble

GLfloat
GLfloat
GLfloat
GLfloat

GLint
GLint
GLint
GLint

GLshort
GLshort
GLshort
GLshort

GLint
GLenum
GLsizei

GLenum
GLenum
GLfloat
GLenum
GLenum

GLenum
GLenum
GLint
GLenum
GLenum

GLenum
GLenum
GLdouble
GLenum
GLenum

GLenum
GLenum
GLfloat
GLenum
GLenum

GLenum
GLenum
GLint
GLenum
GLenum

GLenum
GLint
GLenum
GLsizei
GLint
GLenum
GLenum

GLenum
GLint
GLenum
GLsizei
GLsizei
GLint
GLenum
GLenum

GLenum
GLint
GLenum
GLsizei
GLsizei
GLsizei
GLint
GLenum
GLenum

GLenum
GLenum
GLfloat
GLenum
GLenum

GLenum
GLenum
GLint
GLenum
GLenum

GLenum
GLint
GLint
GLsizei
GLenum
GLenum

GLenum
GLint
GLint
GLint
GLsizei
GLsizei
GLenum
GLenum

GLenum
GLint
GLint
GLint
GLint
GLsizei
GLsizei
GLsizei
GLenum
GLenum

GLdouble
GLdouble
GLdouble
GLfloat
GLfloat
GLfloat
GLdouble
GLdouble

GLfloat
GLfloat

GLint
GLint

GLshort
GLshort

GLdouble
GLdouble
GLdouble

GLfloat
GLfloat
GLfloat

GLint
GLint
GLint

GLshort
GLshort
GLshort

GLdouble
GLdouble
GLdouble
GLdouble

GLfloat
GLfloat
GLfloat
GLfloat

GLint
GLint
GLint
GLint

GLshort
GLshort
GLshort
GLshort

GLint
GLenum
GLsizei

GLint
GLint
GLsizei
GLsizei
GLclampf
GLboolean
GLenum




GLenum
GLint
GLenum
GLsizei
GLsizei
GLsizei
GLint
GLsizei

GLenum
GLint
GLenum
GLsizei
GLsizei
GLint
GLsizei

GLenum
GLint
GLenum
GLsizei
GLint
GLsizei

GLenum
GLint
GLint
GLint
GLint
GLsizei
GLsizei
GLsizei
GLenum
GLsizei

GLenum
GLint
GLint
GLint
GLsizei
GLsizei
GLenum
GLsizei

GLenum
GLint
GLint
GLsizei
GLenum
GLsizei

GLenum
GLint
GLvoid
GLenum
GLenum
GLenum
GLdouble
GLenum

GLenum
GLfloat
GLenum

GLenum
GLint
GLenum

GLenum
GLshort
GLenum

GLenum
GLdouble
GLdouble
GLenum

GLenum
GLfloat
GLfloat
GLenum

GLenum
GLint
GLint
GLenum

GLenum
GLshort
GLshort
GLenum

GLenum
GLdouble
GLdouble
GLdouble
GLenum

GLenum
GLfloat
GLfloat
GLfloat
GLenum

GLenum
GLint
GLint
GLint
GLenum

GLenum
GLshort
GLshort
GLshort
GLenum

GLenum
GLdouble
GLdouble
GLdouble
GLdouble
GLenum

GLenum
GLfloat
GLfloat
GLfloat
GLfloat
GLenum

GLenum
GLint
GLint
GLint
GLint
GLenum

GLenum
GLshort
GLshort
GLshort
GLshort
GLenum

GLfloat

GLdouble

GLenum
GLsizei

GLbyte
GLbyte
GLbyte

GLdouble
GLdouble
GLdouble

GLfloat
GLfloat
GLfloat

GLint
GLint
GLint

GLshort
GLshort
GLshort

GLubyte
GLubyte
GLubyte

GLuint
GLuint
GLuint

GLushort
GLushort
GLushort

GLint
GLenum
GLsizei

GLenum
GLfloat
GLenum

GLenum
GLint
GLenum

GLenum
GLenum
GLenum
GLenum
GLenum


GLsizei
GLenum

GLenum

GLsizei
GLdouble
GLdouble

GLfloat
GLfloat

GLint
GLint

GLshort
GLshort

GLdouble
GLdouble
GLdouble

GLfloat
GLfloat
GLfloat

GLint
GLint
GLint

GLshort
GLshort
GLshort

GLsizei
GLuint
GLsizei

GLuint
GLenum
GLuint
GLenum
GLenum
GLenum
GLint
GLuint
GLenum
GLint
GLuint
GLenum
GLuint
GLenum
GLuint
GLsizei

GLsizei
GLuint
GLuint
GLenum
GLsizeiptr

GLenum
GLenum
GLintptr
GLsizeiptr

GLenum
GLintptr
GLsizeiptr
GLvoid
GLenum
GLenum
GLenum
GLenum
GLenum
GLint
GLenum
GLenum
GLvoid
GLsizei

GLuint
GLdouble
GLuint

GLuint
GLfloat
GLuint

GLuint
GLshort
GLuint

GLuint
GLdouble
GLdouble
GLuint

GLuint
GLfloat
GLfloat
GLuint

GLuint
GLshort
GLshort
GLuint

GLuint
GLdouble
GLdouble
GLdouble
GLuint

GLuint
GLfloat
GLfloat
GLfloat
GLuint

GLuint
GLshort
GLshort
GLshort
GLuint

GLuint

GLuint

GLuint

GLuint
GLubyte
GLubyte
GLubyte
GLubyte
GLuint

GLuint

GLuint

GLuint

GLuint
GLdouble
GLdouble
GLdouble
GLdouble
GLuint

GLuint
GLfloat
GLfloat
GLfloat
GLfloat
GLuint

GLuint

GLuint
GLshort
GLshort
GLshort
GLshort
GLuint

GLuint

GLuint

GLuint

GLuint
GLint
GLenum
GLboolean
GLsizei

GLuint
GLuint
GLuint
GLenum
GLdouble
GLuint
GLenum
GLfloat
GLuint
GLenum
GLint
GLuint
GLenum
GLvoid*
GLuint
GLuint
GLuint
GLenum
GLuint
GLsizei


GLuint
void
GLuint
GLuint
GLuint
GLuint
GLuint
GLuint
GLint
GLfloat
GLint
GLfloat
GLfloat
GLint
GLfloat
GLfloat
GLfloat
GLint
GLfloat
GLfloat
GLfloat
GLfloat
GLint
GLint
GLint
GLint
GLint
GLint
GLint
GLint
GLint
GLint
GLint
GLint
GLint
GLint
GLint
GLsizei

GLint
GLsizei

GLint
GLsizei

GLint
GLsizei

GLint
GLsizei

GLint
GLsizei

GLint
GLsizei

GLint
GLsizei

GLint
GLsizei
GLboolean

GLint
GLsizei
GLboolean

GLint
GLsizei
GLboolean

GLuint
GLuint
GLuint
GLenum
GLint
GLuint
GLenum
GLint
GLuint
GLsizei
GLsizei
GLuint
GLuint
GLsizei
GLsizei
GLchar
GLuint
GLsizei
GLsizei
GLchar
GLuint

GLuint
GLuint
GLsizei
GLsizei
GLint
GLenum
GLchar
GLuint
GLint
GLfloat
GLuint
GLint
GLint
GLuint
GLsizei
GLsizei
GLchar
GLuint
GLuint

GLuint
GLuint
GLsizei
GLsizei
GLint
GLenum
GLchar
GLuint

GLenum
GLenum
GLint
GLuint
GLenum
GLenum
GLenum
GLenum
GLenum
GLuint
GLint
GLsizei
GLboolean

GLint
GLsizei
GLboolean

GLint
GLsizei
GLboolean

GLint
GLsizei
GLboolean

GLint
GLsizei
GLboolean

GLint
GLsizei
GLboolean

GLUnurbs*
GLUtesselator*
GLUnurbs*
GLUnurbs*
GLenum
GLint
GLsizei
GLenum
GLenum
GLint
GLint
GLint

GLenum
GLint
GLsizei
GLenum
GLenum

GLenum
GLint
GLsizei
GLsizei
GLenum
GLenum
GLint
GLint
GLint

GLenum
GLint
GLsizei
GLsizei
GLenum
GLenum

GLenum
GLint
GLsizei
GLsizei
GLsizei
GLenum
GLenum
GLint
GLint
GLint

GLenum
GLint
GLsizei
GLsizei
GLsizei
GLenum
GLenum



GLUquadric*
GLdouble
GLdouble
GLdouble
GLint
GLint
GLUnurbs*
GLUquadric*
GLUtesselator*
GLUquadric*
GLdouble
GLdouble
GLint
GLint
GLUnurbs*
GLUtesselator*
GLUnurbs*
GLUnurbs*
GLUnurbs*
GLenum
GLfloat*
GLUtesselator*
GLenum
GLdouble*
GLUnurbs*



GLdouble
GLdouble
GLdouble
GLdouble
GLdouble
GLdouble
GLdouble
GLdouble
GLdouble
void
void
void
GLUtesselator*
GLenum
GLUnurbs*
GLvoid*
GLUnurbs*
GLvoid*
GLUnurbs*
GLint
GLfloat
GLint
GLfloat
GLint
GLenum
GLUnurbs*
GLenum
GLfloat
GLUnurbs*
GLint
GLfloat*
GLint
GLfloat*
GLint
GLint
GLfloat*
GLint
GLint
GLenum
GLdouble
GLdouble
GLdouble
GLdouble
GLUquadric*
GLdouble
GLdouble
GLint
GLint
GLdouble
GLdouble
GLdouble
GLdouble
GLdouble
GLdouble
GLdouble
GLdouble
GLdouble
GLdouble
GLint
GLdouble
GLdouble
GLdouble



GLdouble*
GLdouble*
GLdouble*
GLUnurbs*
GLint
GLfloat*
GLint
GLenum
GLUquadric*
GLenum
GLUquadric*
GLenum
GLUquadric*
GLenum
GLUquadric*
GLboolean
GLenum
GLsizei
GLsizei
GLenum

GLsizei
GLsizei
GLenum
GLvoid*
GLUquadric*
GLdouble
GLint
GLint
GLUtesselator*
GLUtesselator*
GLvoid*
GLUtesselator*
GLUtesselator*
GLUtesselator*
GLdouble
GLdouble
GLdouble
GLUtesselator*
GLenum
GLdouble
GLUtesselator*
GLdouble
GLvoid*
GLdouble
GLdouble
GLdouble



GLdouble*
GLdouble*
GLdouble*
GLdouble
GLdouble
GLdouble
GLdouble



GLdouble
GLdouble
GLdouble*
GLdouble*
GLdouble*
GLdouble*
int
char


int
int
int
int
void

int
int
int
int
int
int
void
int
void
void
int


int
int
int
int
void
void
void
void
void
void
int
int
int
GLenum
GLenum
int
void
void
void
GLenum
void
int
void
void
int
void
int

int

int
int

int
int

int
int
int
int
int
GLfloat
GLfloat
GLfloat
int
int
int
GLenum
GLenum

void
GLenum

void
int
void
int
void
int
void
int
void

void

GLdouble
GLint
GLint
GLdouble
GLint
GLint
GLdouble
GLdouble
GLint
GLint
GLdouble
GLdouble
GLint
GLint
GLdouble
GLdouble
GLdouble
GLdouble
GLint
GLint
GLdouble
GLdouble
GLint
GLint
void
void
GLdouble
GLdouble
void
void
void
void
void
void
GLenum
void
void
int
int
int
int
int
int
int
int
void
int
int
void

void
void
GLenum
void GL.glVertexBlendARB(Int i0);
void GL.glWindowPos2dARB(Float f0, Float f1);
void GL.glWindowPos2fARB(Float f0, Float f1);
void GL.glWindowPos2iARB(Int i0, Int i1);
void GL.glWindowPos2sARB(Int i0, Int i1);
void GL.glWindowPos3dARB(Float f0, Float f1, Float f2);
void GL.glWindowPos3fARB(Float f0, Float f1, Float f2);
void GL.glWindowPos3iARB(Int i0, Int i1, Int i2);
void GL.glWindowPos3sARB(Int i0, Int i1, Int i2);
void GL.glVertexAttrib1dARB(Int i0, Float f1);
void GL.glVertexAttrib1fARB(Int i0, Float f1);
void GL.glVertexAttrib1sARB(Int i0, Int i1);
void GL.glVertexAttrib2dARB(Int i0, Float f1, Float f2);
void GL.glVertexAttrib2fARB(Int i0, Float f1, Float f2);
void GL.glVertexAttrib2sARB(Int i0, Int i1, Int i2);
void GL.glVertexAttrib3dARB(Int i0, Float f1, Float f2, Float f3);
void GL.glVertexAttrib3fARB(Int i0, Float f1, Float f2, Float f3);
void GL.glVertexAttrib3sARB(Int i0, Int i1, Int i2, Int i3);
void GL.glVertexAttrib4dARB(Int i0, Float f1, Float f2, Float f3, Float f4);
void GL.glVertexAttrib4fARB(Int i0, Float f1, Float f2, Float f3, Float f4);
void GL.glVertexAttrib4sARB(Int i0, Int i1, Int i2, Int i3, Int i4);
void GL.glDisableVertexAttribArrayARB(Int i0);
void GL.glEnableVertexAttribArrayARB(Int i0);
void GL.glUniform1fARB(Int i0, Float f1);
void GL.glUniform2fARB(Int i0, Float f1, Float f2);
void GL.glUniform3fARB(Int i0, Float f1, Float f2, Float f3);
void GL.glUniform4fARB(Int i0, Float f1, Float f2, Float f3, Float f4);
void GL.glUniform1iARB(Int i0, Int i1);
void GL.glUniform2iARB(Int i0, Int i1, Int i2);
void GL.glUniform3iARB(Int i0, Int i1, Int i2, Int i3);
void GL.glUniform4iARB(Int i0, Int i1, Int i2, Int i3, Int i4);
void GL.glUnlockArraysEXT();
void GL.glSecondaryColor3dEXT(Float f0, Float f1, Float f2);
void GL.glSecondaryColor3fEXT(Float f0, Float f1, Float f2);
void GL.glSecondaryColor3iEXT(Int i0, Int i1, Int i2);
void GL.glSecondaryColor3sEXT(Int i0, Int i1, Int i2);
void GL.glSecondaryColor3uiEXT(Int i0, Int i1, Int i2);
void GL.glFogCoordfEXT(Float f0);
void GL.glFogCoorddEXT(Float f0);
void GL.glEndTransformFeedbackEXT();
void GL.glUniformBufferEXT(Int i0, Int i1, Int i2);
Int GL.glGetUniformBufferSizeEXT(Int i0, Int i1);
void GL.glClearColorIiEXT(Int i0, Int i1, Int i2, Int i3);
void GL.glClearColorIuiEXT(Int i0, Int i1, Int i2, Int i3);
void GL.glVertexAttribI1iEXT(Int i0, Int i1);
void GL.glVertexAttribI2iEXT(Int i0, Int i1, Int i2);
void GL.glVertexAttribI3iEXT(Int i0, Int i1, Int i2, Int i3);
void GL.glVertexAttribI4iEXT(Int i0, Int i1, Int i2, Int i3, Int i4);
void GL.glVertexAttribI1uiEXT(Int i0, Int i1);
void GL.glVertexAttribI2uiEXT(Int i0, Int i1, Int i2);
void GL.glVertexAttribI3uiEXT(Int i0, Int i1, Int i2, Int i3);
void GL.glVertexAttribI4uiEXT(Int i0, Int i1, Int i2, Int i3, Int i4);
void GL.glUniform1uiEXT(Int i0, Int i1);
void GL.glUniform2uiEXT(Int i0, Int i1, Int i2);
void GL.glUniform3uiEXT(Int i0, Int i1, Int i2, Int i3);
void GL.glUniform4uiEXT(Int i0, Int i1, Int i2, Int i3, Int i4);
void GL.glGetUniformuivEXT(Int i0, Int i1, Int i2);
void GL.glBindVertexArrayAPPLE(Int i0);
void GL.glSetFenceAPPLE(Int i0);
void GL.glFinishFenceAPPLE(Int i0);
void GL.glFlushRenderAPPLE();
void GL.glFinishRenderAPPLE();
void GL.glSwapAPPLE();
void GL.glArrayElement(Int i0);
void GL.glCallList(Int i0);
void GL.glClearAccum(Float f0, Float f1, Float f2, Float f3);
void GL.glClearIndex(Float f0);
void GL.glClearStencil(Int i0);
void GL.glColor3d(Float f0, Float f1, Float f2);
void GL.glColor3f(Float f0, Float f1, Float f2);
void GL.glColor3i(Int i0, Int i1, Int i2);
void GL.glColor3s(Int i0, Int i1, Int i2);
void GL.glColor3ui(Int i0, Int i1, Int i2);
void GL.glColor4d(Float f0, Float f1, Float f2, Float f3);
void GL.glColor4f(Float f0, Float f1, Float f2, Float f3);
void GL.glColor4i(Int i0, Int i1, Int i2, Int i3);
void GL.glColor4s(Int i0, Int i1, Int i2, Int i3);
void GL.glColor4ui(Int i0, Int i1, Int i2, Int i3);
void GL.glEnd();
void GL.glEndList();
void GL.glEvalCoord1d(Float f0);
void GL.glEvalCoord1f(Float f0);
void GL.glEvalCoord2d(Float f0, Float f1);
void GL.glEvalCoord2f(Float f0, Float f1);
void GL.glEvalPoint1(Int i0);
void GL.glEvalPoint2(Int i0, Int i1);
void GL.glFinish();
void GL.glFlush();
void GL.glFrustum(Float f0, Float f1, Float f2, Float f3, Float f4, Float f5);
void GL.glIndexMask(Int i0);
void GL.glIndexd(Float f0);
void GL.glIndexf(Float f0);
void GL.glIndexi(Int i0);
void GL.glIndexs(Int i0);
void GL.glInitNames();
void GL.glLineWidth(Float f0);
void GL.glListBase(Int i0);
void GL.glLoadIdentity();
void GL.glLoadName(Int i0);
void GL.glMapGrid1d(Int i0, Float f1, Float f2);
void GL.glMapGrid1f(Int i0, Float f1, Float f2);
void GL.glMapGrid2d(Int i0, Float f1, Float f2, Int i3, Float f4, Float f5);
void GL.glMapGrid2f(Int i0, Float f1, Float f2, Int i3, Float f4, Float f5);
void GL.glNormal3d(Float f0, Float f1, Float f2);
void GL.glNormal3f(Float f0, Float f1, Float f2);
void GL.glNormal3i(Int i0, Int i1, Int i2);
void GL.glNormal3s(Int i0, Int i1, Int i2);
void GL.glOrtho(Float f0, Float f1, Float f2, Float f3, Float f4, Float f5);
void GL.glPassThrough(Float f0);
void GL.glPixelZoom(Float f0, Float f1);
void GL.glPointSize(Float f0);
void GL.glPolygonOffset(Float f0, Float f1);
void GL.glPopAttrib();
void GL.glPopClientAttrib();
void GL.glPopMatrix();
void GL.glPopName();
void GL.glPushMatrix();
void GL.glPushName(Int i0);
void GL.glRasterPos2d(Float f0, Float f1);
void GL.glRasterPos2f(Float f0, Float f1);
void GL.glRasterPos2i(Int i0, Int i1);
void GL.glRasterPos2s(Int i0, Int i1);
void GL.glRasterPos3d(Float f0, Float f1, Float f2);
void GL.glRasterPos3f(Float f0, Float f1, Float f2);
void GL.glRasterPos3i(Int i0, Int i1, Int i2);
void GL.glRasterPos3s(Int i0, Int i1, Int i2);
void GL.glRasterPos4d(Float f0, Float f1, Float f2, Float f3);
void GL.glRasterPos4f(Float f0, Float f1, Float f2, Float f3);
void GL.glRasterPos4i(Int i0, Int i1, Int i2, Int i3);
void GL.glRasterPos4s(Int i0, Int i1, Int i2, Int i3);
void GL.glRectd(Float f0, Float f1, Float f2, Float f3);
void GL.glRectf(Float f0, Float f1, Float f2, Float f3);
void GL.glRecti(Int i0, Int i1, Int i2, Int i3);
void GL.glRects(Int i0, Int i1, Int i2, Int i3);
void GL.glRotated(Float f0, Float f1, Float f2, Float f3);
void GL.glRotatef(Float f0, Float f1, Float f2, Float f3);
void GL.glScaled(Float f0, Float f1, Float f2);
void GL.glScalef(Float f0, Float f1, Float f2);
void GL.glStencilMask(Int i0);
void GL.glTexCoord1d(Float f0);
void GL.glTexCoord1f(Float f0);
void GL.glTexCoord1i(Int i0);
void GL.glTexCoord1s(Int i0);
void GL.glTexCoord2d(Float f0, Float f1);
void GL.glTexCoord2f(Float f0, Float f1);
void GL.glTexCoord2i(Int i0, Int i1);
void GL.glTexCoord2s(Int i0, Int i1);
void GL.glTexCoord3d(Float f0, Float f1, Float f2);
void GL.glTexCoord3f(Float f0, Float f1, Float f2);
void GL.glTexCoord3i(Int i0, Int i1, Int i2);
void GL.glTexCoord3s(Int i0, Int i1, Int i2);
void GL.glTexCoord4d(Float f0, Float f1, Float f2, Float f3);
void GL.glTexCoord4f(Float f0, Float f1, Float f2, Float f3);
void GL.glTexCoord4i(Int i0, Int i1, Int i2, Int i3);
void GL.glTexCoord4s(Int i0, Int i1, Int i2, Int i3);
void GL.glTranslated(Float f0, Float f1, Float f2);
void GL.glTranslatef(Float f0, Float f1, Float f2);
void GL.glVertex2d(Float f0, Float f1);
void GL.glVertex2f(Float f0, Float f1);
void GL.glVertex2i(Int i0, Int i1);
void GL.glVertex2s(Int i0, Int i1);
void GL.glVertex3d(Float f0, Float f1, Float f2);
void GL.glVertex3f(Float f0, Float f1, Float f2);
void GL.glVertex3i(Int i0, Int i1, Int i2);
void GL.glVertex3s(Int i0, Int i1, Int i2);
void GL.glVertex4d(Float f0, Float f1, Float f2, Float f3);
void GL.glVertex4f(Float f0, Float f1, Float f2, Float f3);
void GL.glVertex4i(Int i0, Int i1, Int i2, Int i3);
void GL.glVertex4s(Int i0, Int i1, Int i2, Int i3);
void GL.glFogCoordf(Float f0);
void GL.glFogCoordd(Float f0);
void GL.glSecondaryColor3d(Float f0, Float f1, Float f2);
void GL.glSecondaryColor3f(Float f0, Float f1, Float f2);
void GL.glSecondaryColor3i(Int i0, Int i1, Int i2);
void GL.glSecondaryColor3s(Int i0, Int i1, Int i2);
void GL.glSecondaryColor3ui(Int i0, Int i1, Int i2);
void GL.glWindowPos2d(Float f0, Float f1);
void GL.glWindowPos2f(Float f0, Float f1);
void GL.glWindowPos2i(Int i0, Int i1);
void GL.glWindowPos2s(Int i0, Int i1);
void GL.glWindowPos3d(Float f0, Float f1, Float f2);
void GL.glWindowPos3f(Float f0, Float f1, Float f2);
void GL.glWindowPos3i(Int i0, Int i1, Int i2);
void GL.glWindowPos3s(Int i0, Int i1, Int i2);
void GL.glVertexAttrib1d(Int i0, Float f1);
void GL.glVertexAttrib1f(Int i0, Float f1);
void GL.glVertexAttrib1s(Int i0, Int i1);
void GL.glVertexAttrib2d(Int i0, Float f1, Float f2);
void GL.glVertexAttrib2f(Int i0, Float f1, Float f2);
void GL.glVertexAttrib2s(Int i0, Int i1, Int i2);
void GL.glVertexAttrib3d(Int i0, Float f1, Float f2, Float f3);
void GL.glVertexAttrib3f(Int i0, Float f1, Float f2, Float f3);
void GL.glVertexAttrib3s(Int i0, Int i1, Int i2, Int i3);
void GL.glVertexAttrib4d(Int i0, Float f1, Float f2, Float f3, Float f4);
void GL.glVertexAttrib4f(Int i0, Float f1, Float f2, Float f3, Float f4);
void GL.glVertexAttrib4s(Int i0, Int i1, Int i2, Int i3, Int i4);
void GL.glEnableVertexAttribArray(Int i0);
void GL.glDisableVertexAttribArray(Int i0);
void GL.glDeleteShader(Int i0);
void GL.glDetachShader(Int i0, Int i1);
void GL.glCompileShader(Int i0);
Int GL.glCreateProgram();
void GL.glAttachShader(Int i0, Int i1);
void GL.glLinkProgram(Int i0);
void GL.glUseProgram(Int i0);
void GL.glDeleteProgram(Int i0);
void GL.glValidateProgram(Int i0);
void GL.glUniform1f(Int i0, Float f1);
void GL.glUniform2f(Int i0, Float f1, Float f2);
void GL.glUniform3f(Int i0, Float f1, Float f2, Float f3);
void GL.glUniform4f(Int i0, Float f1, Float f2, Float f3, Float f4);
void GL.glUniform1i(Int i0, Int i1);
void GL.glUniform2i(Int i0, Int i1, Int i2);
void GL.glUniform3i(Int i0, Int i1, Int i2, Int i3);
void GL.glUniform4i(Int i0, Int i1, Int i2, Int i3, Int i4);
void GL.glGetUniformfv(Int i0, Int i1, Float f2);
void GL.glGetUniformiv(Int i0, Int i1, Int i2);
void GL.gluLookAt(Float f0, Float f1, Float f2, Float f3, Float f4, Float f5, Float f6, Float f7, Float f8);
void GL.gluOrtho2D(Float f0, Float f1, Float f2, Float f3);
void GL.gluPerspective(Float f0, Float f1, Float f2, Float f3);
void GL.gluPickMatrix(Float f0, Float f1, Float f2, Float f3, Int i4);
void GL.glutInitWindowPosition(Int i0, Int i1);
void GL.glutInitWindowSize(Int i0, Int i1);
void GL.glutMainLoop();
Int GL.glutCreateSubWindow(Int i0, Int i1, Int i2, Int i3, Int i4);
void GL.glutDestroyWindow(Int i0);
void GL.glutPostRedisplay();
void GL.glutPostWindowRedisplay(Int i0);
void GL.glutSwapBuffers();
Int GL.glutGetWindow();
void GL.glutSetWindow(Int i0);
void GL.glutPositionWindow(Int i0, Int i1);
void GL.glutReshapeWindow(Int i0, Int i1);
void GL.glutPopWindow();
void GL.glutPushWindow();
void GL.glutIconifyWindow();
void GL.glutShowWindow();
void GL.glutHideWindow();
void GL.glutFullScreen();
void GL.glutSetCursor(Int i0);
void GL.glutWarpPointer(Int i0, Int i1);
void GL.glutCheckLoop();
void GL.glutEstablishOverlay();
void GL.glutRemoveOverlay();
void GL.glutPostOverlayRedisplay();
void GL.glutPostWindowOverlayRedisplay(Int i0);
void GL.glutShowOverlay();
void GL.glutHideOverlay();
void GL.glutDestroyMenu(Int i0);
Int GL.glutGetMenu();
void GL.glutSetMenu(Int i0);
void GL.glutRemoveMenuItem(Int i0);
void GL.glutAttachMenu(Int i0);
void GL.glutDetachMenu(Int i0);
void GL.glutSetColor(Int i0, Float f1, Float f2, Float f3);
Float GL.glutGetColor(Int i0, Int i1);
void GL.glutCopyColormap(Int i0);
Int GL.glutGetModifiers();
void GL.glutBitmapCharacter(, Int i1);
Int GL.glutBitmapWidth(, Int i1);
void GL.glutStrokeCharacter(, Int i1);
Int GL.glutStrokeWidth(, Int i1);
void GL.glutWireSphere(Float f0, Int i1, Int i2);
void GL.glutSolidSphere(Float f0, Int i1, Int i2);
void GL.glutWireCone(Float f0, Float f1, Int i2, Int i3);
void GL.glutSolidCone(Float f0, Float f1, Int i2, Int i3);
void GL.glutWireCube(Float f0);
void GL.glutSolidCube(Float f0);
void GL.glutWireTorus(Float f0, Float f1, Int i2, Int i3);
void GL.glutSolidTorus(Float f0, Float f1, Int i2, Int i3);
void GL.glutWireDodecahedron();
void GL.glutSolidDodecahedron();
void GL.glutWireTeapot(Float f0);
void GL.glutSolidTeapot(Float f0);
void GL.glutWireOctahedron();
void GL.glutSolidOctahedron();
void GL.glutWireTetrahedron();
void GL.glutSolidTetrahedron();
void GL.glutWireIcosahedron();
void GL.glutSolidIcosahedron();
void GL.glutSetupVideoResizing();
void GL.glutStopVideoResizing();
void GL.glutVideoResize(Int i0, Int i1, Int i2, Int i3);
void GL.glutVideoPan(Int i0, Int i1, Int i2, Int i3);
void GL.glutReportErrors();
void GL.glutIgnoreKeyRepeat(Int i0);
void GL.glutSetKeyRepeat(Int i0);
void GL.glutForceJoystickFunc();
Int GL.glutEnterGameMode();
void GL.glutLeaveGameMode();
