# Makefile for konoha package
# This makefile is generated by gen_pkgmake.k
# shinpei(c)2009

CC = gcc
CFLAGS = -O2 -Wall -fmessage-length=0
LDLIBS = -lkonoha 
library = aobench.dylib
.PHONY: all
all: $(library)

objs = aobench.o
aobench.o: aobench.c
	$(CC) $(CFLAGS) -o $@ -c $^
$(library): $(objs)
	$(CC) -dynamiclib -Wl -o $@ $^ $(LDLIBS)
.PHONY: clean
clean:
	$(RM) -rf $(objs) $(library)

.PHONY: konoha_install
konoha_install: $(library)
	mkdir -p .konoha/aobench
	cp $(library) .konoha/aobench
	cp aobench.k .konoha/aobench
